// Top-level build file : déclare les plugins utilisés par les sous-projets
// (juste "app" ici), sans les appliquer directement (apply false).
plugins {
    id 'com.android.application' version '8.7.2' apply false
    id 'org.jetbrains.kotlin.android' version '2.0.21' apply false
    id 'com.google.gms.google-services' version '4.4.2' apply false
}
